config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :menu_types do
    resources :menus, only: [:index]
  end

  resources :tags do
    resources :menu_items, only: [:index]
  end

  scope "/menu_items" do
    get "dollar_menu", to: "menu_items#dollar_menu"
    get "under_five", to: "menu_items#under_five"
    get "under_ten", to: "menu_items#under_ten"
    get "under_twenty", to: "menu_items#under_twenty"
  end

  resources :menu_items

  resources :menus
  resources :menus do
    resources :menu_items, only: [:index, :new]
  end

  resources :restaurants
  resources :restaurants do
    resources :menus, only: [:index, :new]
  end

  resources :users, except: [:index]
  resources :users do
    resources :restaurants, only: [:index]
    resources :menus, only: [:index]
    resources :menu_items, only: [:index]
  end

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  post "logout", to: "sessions#destroy"

  get "/auth/facebook/callback", to: "sessions#create"

  get "register", to: "users#new"
  post "register", to: "users#create"

  get "about", to: "application#about"
  get "search", to: "application#search"

  root "application#index"
end

app/models/menu.rb
class Menu < ApplicationRecord
    belongs_to :restaurant
    has_many :menu_types
    has_many :menu_items, dependent: :destroy
    has_many :tags, through: :menu_items

    validates :name, presence: true, length: { maximum: 100 }
    validates :description, presence: true, length: { maximum: 1000 }
end

app/models/menu_type.rb
class MenuType < ApplicationRecord
    has_many :menus
    has_many :menu_items, through: :menus

    validates :name, presence: true, uniqueness: true, length: { maximum: 100 }
end
 

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    #before_action :authorize?, only: [:create, :edit, :update, :destroy]

    def new
        return redirect_to "/login" if !helpers.logged_in?
        @menu = Menu.new
    end

    def create
        @menu = Menu.new(menu_params)
        @menu.restaurant_id = params[:restaurant_id]
        authorize?(@menu.restaurant.user_id)
        if !@menu.valid?
            return render :new
        else
            @menu.save
            redirect_to menu_path(@menu)
        end
    end

    def index
        if params.has_key?(:menu_type_id)
            @menus = Menu.where(menu_type_id: params[:menu_type_id])
        elsif params.has_key?(:restaurant_id)
            @menus = Menu.where(restaurant_id: params[:restaurant_id])
        elsif params.has_key?(:user_id)
            @menus = User.find(params[:user_id]).menus
        else
            @menus = Menu.all
        end
    end

    def show
        @menu = Menu.find(params[:id])
    end

    def edit
        @menu = Menu.find(params[:id])
        authorize?(@menu.restaurant.user_id)
    end

    def update
        @menu = Menu.find(params[:id])
        authorize?(@menu.restaurant.user_id)
        if !@menu.update(menu_params)
            return render :edit
        else
            redirect_to menu_path(@menu)
        end
    end

    def destroy
        @menu = Menu.find(params[:id])
        authorize?(@menu.restaurant.user_id)
        @menu.destroy
        redirect_to restaurant_path(@menu.restaurant)
    end

    def menu_params
        params.require(:menu).permit(:name, :description, :restaurant_id)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<% if @menu.errors.any? %>
    <div id="error_explanation">
        <h2>There were some errors:</h2>
        <ul>
            <% @menu.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="form">
    <%= form_for @menu do |f| %>
        <div class="field <%= " field_with_errors" if @menu.errors[:name].any? %>">
            <%= f.label :name, "Name" %>
            <br>
            <%= f.text_field :name %>
        </div>
        <div class="field <%= " field_with_errors" if @menu.errors[:description].any? %>">
            <%= f.label :description, "Description" %>
            <br>
            <%= f.text_field :description %>
        </div>
        <% if !params.has_key?(:restaurant_id) %>
            <div class="field <%= " field_with_errors" if @menu.errors[:restaurant_id].any? %>">
                <%= f.label :restaurant_id, "Restaurant" %>
                <br>
                <%= f.collection_select :restaurant_id, current_user.restaurants, :id, :name, prompt: true %>
            </div>
        <% else %>
            <input type="hidden" name="restaurant_id" value="<%= params[:restaurant_id] %>">
        <% end %>
        <%= f.submit "Submit" %>
    <% end %>
</div>

app/views/menus/edit.html.erb
<h1>Edit Menu</h1>
<%= render "form" %>

app/views/menus/index.html.erb
<h1>Menus</h1>
<% if params.has_key?(:user_id) && params[:user_id] == current_user.id.to_s %>
    <br>
    <div class="wrapper">
        <a href="<%= new_menu_path %>"><button>New Menu</button></a>
    </div>
<% end %>
<br>
<div class="card">
    <div class="container">
        <% if @menus.any? %>
            <% @menus.each do |menu| %>
                <h1><%= link_to menu.name, menu %></h1>
                <h2><%= truncate(menu.description, length: 30) %></h2>
                <br>
            <% end %>
        <% else %>
            <h2>There are currently no menus.</h2>
        <% end %>
    </div>
</div>

app/views/menus/new.html.erb
<h1>New Menu</h1>
<%= render "form" %>

app/views/menus/show.html.erb
<h1><%= @menu.name %></h1>

<% if @menu.restaurant.user == current_user %>
    <br>
    <div class="wrapper">
        <a href="<%= edit_menu_path(@menu) %>"><button>Edit</button></a>
        <%= form_for @menu, html: { method: :delete } do |f| %>
            <%= f.submit "Delete" %>
        <% end %>
    </div>
    <br>
<% end %>

<h3><%= @menu.description %></h3>
<h2><%= link_to "🏨 #{@menu.restaurant.name}", @menu.restaurant %></h2>

<hr>

<h1><%= link_to "Menu Items", menu_menu_items_path(@menu) %></h1>

<% if @menu.restaurant.user == current_user %>
    <br>
    <div class="wrapper">
        <a href="<%= new_menu_menu_item_path(@menu) %>"><button>New Menu Item</button></a>
    </div>
<% end %>
<br>
<div class="card">
    <div class="container">
        <% if @menu.menu_items.any? %>
            <% @menu.menu_items.each do |menu_item| %>
                <h1><%= link_to menu_item.name, menu_item %></h1>
                <h1><%= "$#{menu_item.price}" %></h1>
                <h2><%= truncate(menu_item.description, length: 30) %></h2>
                <br>
            <% end %>
        <% else %>
            <h2>There are currently no menu items.</h2>
        <% end %>
    </div>
</div>