config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :menu_types do
    resources :menus, only: [:index]
  end

  resources :tags do
    resources :menu_items, only: [:index]
  end

  scope "/menu_items" do
    get "dollar_menu", to: "menu_items#dollar_menu"
    get "under_five", to: "menu_items#under_five"
    get "under_ten", to: "menu_items#under_ten"
    get "under_twenty", to: "menu_items#under_twenty"
  end

  resources :menu_items

  resources :menus
  resources :menus do
    resources :menu_items, only: [:index, :new]
  end

  resources :restaurants
  resources :restaurants do
    resources :menus, only: [:index, :new]
  end

  resources :users, except: [:index]
  resources :users do
    resources :restaurants, only: [:index]
    resources :menus, only: [:index]
    resources :menu_items, only: [:index]
  end

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  post "logout", to: "sessions#destroy"

  get "/auth/facebook/callback", to: "sessions#create"

  get "register", to: "users#new"
  post "register", to: "users#create"

  get "about", to: "application#about"
  get "search", to: "application#search"

  root "application#index"
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
    belongs_to :menu
    has_many :menu_items_tags
    has_many :tags, through: :menu_items_tags, dependent: :destroy

    validates :name, presence: true, length: { maximum: 100 }
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
    validates :description, presence: true, length: { maximum: 1000 }

    scope :dollar_menu, -> { where("price < 2") }
    scope :under_five, -> { where("price < 5") }
    scope :under_ten, -> { where("price < 10") }
    scope :under_twenty, -> { where("price < 20") }
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
    #before_action :authorize?, only: [:create, :edit, :update, :destroy]

    def new
        return redirect_to "/login" if !helpers.logged_in?
        @menu_item = MenuItem.new
    end
    
    def create
        @menu_item = MenuItem.new(menu_item_params)
        @menu_item.menu_id = params[:menu_id] || params[:menu_item][:menu_id] #Different nested routes have different param hash structures
        authorize?(@menu_item.menu.restaurant.user_id)
        if !@menu_item.valid?
            return render :new
        else
            @menu_item.save
            redirect_to menu_item_path(@menu_item)
        end
    end

    def index
        if params.has_key?(:tag_id)
            #CREATE JOIN TABLE FOR TAGS (menu_items_tags)
            #@menu_items = MenuItem.where(tag_id: params[:tag_id])
        elsif params.has_key?(:menu_id)
            @menu_items = MenuItem.where(menu_id: params[:menu_id])
        elsif params.has_key?(:user_id)
            @menu_items = User.find(params[:user_id]).menu_items
        else
            @menu_items = MenuItem.all
        end
    end

    def show
        @menu_item = MenuItem.find(params[:id])
    end

    def edit
        @menu_item = MenuItem.find(params[:id])
        authorize?(@menu_item.menu.restaurant.user_id)
    end

    def update
        @menu_item = MenuItem.find(params[:id])
        authorize?(@menu_item.menu.restaurant.user_id)
        if !@menu_item.update(menu_item_params)
            return render :edit
        else
            redirect_to menu_item_path(@menu_item)
        end
    end

    def destroy
        @menu_item = MenuItem.find(params[:id])
        authorize?(@menu_item.menu.restaurant.user_id)
        @menu_item.destroy
        redirect_to menu_path(@menu_item.menu)
    end

    def dollar_menu
        @menu_items = MenuItem.dollar_menu
        @scope_name = "Dollar Menu"
        render "scoped"
    end

    def under_five
        @menu_items = MenuItem.under_five
        @scope_name = "Under Five"
        render "scoped"
    end

    def under_ten
        @menu_items = MenuItem.under_ten
        @scope_name = "Under Ten"
        render "scoped"
    end

    def under_twenty
        @menu_items = MenuItem.under_twenty
        @scope_name = "Under Twenty"
        render "scoped"
    end

    def menu_item_params
        params.require(:menu_item).permit(:name, :price, :description, :menu_id, tag_ids: [])
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<% if @menu_item.errors.any? %>
    <div id="error_explanation">
        <h2>There were some errors:</h2>
        <ul>
            <% @menu_item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="form">
    <%= form_for @menu_item do |f| %>
        <div class="field <%= " field_with_errors" if @menu_item.errors[:name].any? %>">
            <%= f.label :name, "Name" %>
            <br>
            <%= f.text_field :name %>
        </div>
        <div class="field <%= " field_with_errors" if @menu_item.errors[:price].any? %>">
            <%= f.label :price, "Price" %>
            <br>
            <%= f.text_field :price %>
        </div>
        <div class="field <%= " field_with_errors" if @menu_item.errors[:description].any? %>">
            <%= f.label :description, "Description" %>
            <br>
            <%= f.text_field :description %>
        </div>
        <div class="field <%= " field_with_errors" if @menu_item.errors[:tags].any? %>">
            <%= f.label :description, "Tags" %>
            <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |b| %>
                <div class="collection-check-box">
                    <%= b.check_box %>
                    <%= b.label %>
                </div>
            <% end %>
        </div>
        <% if !params.has_key?(:menu_id) %>
            <div class="field <%= " field_with_errors" if @menu_item.errors[:menu_id].any? %>">
                <%= f.label :menu_id, "Menu" %>
                <br>
                <%= f.collection_select :menu_id, current_user.menus, :id, :name, prompt: true %>
            </div>
        <% else %>
            <input type="hidden" name="menu_id" value="<%= params[:menu_id] %>">
        <% end %>
        <%= f.submit "Submit" %>
    <% end %>
</div>

app/views/menu_items/edit.html.erb
<h1>Edit Menu Item</h1>
<%= render "form" %>

app/views/menu_items/index.html.erb
<h1>Menu Items</h1>
<% if params.has_key?(:user_id) && params[:user_id] == current_user.id.to_s %>
    <br>
    <div class="wrapper">
        <a href="<%= new_menu_item_path %>"><button>New Menu Item</button></a>
    </div>
<% else %>
<br>
    <div class="wrapper">
        <a href="<%= "/menu_items/dollar_menu" %>"><button class="tag">Dollar Menu</button></a>
        <a href="<%= "/menu_items/under_five" %>"><button class="tag">Under $5</button></a>
        <a href="<%= "/menu_items/under_ten" %>"><button class="tag">Under $10</button></a>
        <a href="<%= "/menu_items/under_twenty" %>"><button class="tag">Under $20</button></a>
    </div>
<% end %>
<br>
<div class="card">
    <div class="container">
        <% if @menu_items.any? %>
            <% @menu_items.each do |menu_item| %>
                <h1><%= link_to menu_item.name, menu_item %></h1>
                <h2><%= truncate(menu_item.description, length: 30) %></h2>
                <br>
            <% end %>
        <% else %>
            <h2>There are currently no menu items.</h2>
        <% end %>
    </div>
</div>

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>
<%= render "form" %>

app/views/menu_items/scoped.html.erb
<h1>Menu Items - <%= @scope_name %></h1>
<% if params.has_key?(:user_id) && params[:user_id] == current_user.id.to_s %>
    <br>
    <div class="wrapper">
        <a href="<%= new_menu_item_path %>"><button>New Menu Item</button></a>
    </div>
<% end %>
<br>
<div class="card">
    <div class="container">
        <% @menu_items.each do |menu_item| %>
            <h1><%= link_to menu_item.name, menu_item %></h1>
            <h2><%= truncate(menu_item.description, length: 20) %></h2>
        <% end %>
    </div>
</div>

app/views/menu_items/show.html.erb
<h1><%= @menu_item.name %></h1>

<br>

<% if @menu_item.menu.restaurant.user == current_user %>
    <div class="wrapper">
        <a href="<%= edit_menu_item_path(@menu_item) %>"><button>Edit</button></a>
        <%= form_for @menu_item, html: { method: :delete } do |f| %>
            <%= f.submit "Delete" %>
        <% end %>
    </div>
    <br>
<% end %>

<% if @menu_item.tags.any? %>
    <div class="wrapper">
        <% @menu_item.tags.each do |tag| %>
            <a href="<%= tag_path(tag) %>"><button class="tag"><%= tag.name %></button></a>
        <% end %>
    </div>
    <br>
<% end %>

<h3><%= @menu_item.description %></h3>
<h2><%= "$#{@menu_item.price}" %></h2>
<h2>📃 <%= link_to @menu_item.menu.name, @menu_item.menu %></h2>
<h2>🏨 <%= link_to @menu_item.menu.restaurant.name, @menu_item.menu.restaurant %></h2>