config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :menu_types do
    resources :menus, only: [:index]
  end

  resources :tags do
    resources :menu_items, only: [:index]
  end

  scope "/menu_items" do
    get "dollar_menu", to: "menu_items#dollar_menu"
    get "under_five", to: "menu_items#under_five"
    get "under_ten", to: "menu_items#under_ten"
    get "under_twenty", to: "menu_items#under_twenty"
  end

  resources :menu_items

  resources :menus
  resources :menus do
    resources :menu_items, only: [:index, :new]
  end

  resources :restaurants
  resources :restaurants do
    resources :menus, only: [:index, :new]
  end

  resources :users, except: [:index]
  resources :users do
    resources :restaurants, only: [:index]
    resources :menus, only: [:index]
    resources :menu_items, only: [:index]
  end

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  post "logout", to: "sessions#destroy"

  get "/auth/facebook/callback", to: "sessions#create"

  get "register", to: "users#new"
  post "register", to: "users#create"

  get "about", to: "application#about"
  get "search", to: "application#search"

  root "application#index"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :user
    has_many :menus, dependent: :destroy
    has_many :menu_items, through: :menus
    
    validates :name, presence: true, uniqueness: true, length: { maximum: 100 }
    validates :description, presence: true, length: { maximum: 1000 }
    validates :website, length: { maximum: 400 }
    validates :phone_number, format: { with: /\d{3}-\d{3}-\d{4}/, message: "Not a proper phone number. Phone number should follow this format: (XXX-XXX-XXXX)" }
    validates :address, presence: true, length: { maximum: 400 }
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    #before_action :authorize?, only: [:create, :edit, :update, :destroy]

    def new
        return redirect_to "/login" if !helpers.logged_in?
        @restaurant = Restaurant.new
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        @restaurant.user = helpers.current_user
        if !@restaurant.valid?
            return render :new
        else
            @restaurant.save
            redirect_to restaurant_path(@restaurant)
        end
    end

    def index
        if params.has_key?(:user_id)
            @restaurants = User.find(params[:user_id]).restaurants
        else
            @restaurants = Restaurant.all
        end
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end

    def edit
        @restaurant = Restaurant.find(params[:id])
        authorize?(@restaurant.user_id)
    end

    def update
        @restaurant = Restaurant.find(params[:id])
        authorize?(@restaurant.user_id)
        if !@restaurant.update(restaurant_params)
            return render :edit
        else
            redirect_to restaurant_path(@restaurant)
        end
    end

    def destroy
        @restaurant = Restaurant.find(params[:id])
        authorize?(@restaurant.user_id)
        @restaurant.destroy
        redirect_to user_restaurants_path(@restaurant.user)
    end

    def restaurant_params
        params.require(:restaurant).permit(:name, :description, :website, :phone_number, :address)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
    <div id="error_explanation">
        <h2>There were some errors:</h2>
        <ul>
            <% @restaurant.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="form">
    <%= form_for @restaurant do |f| %>
        <div class="field <%= " field_with_errors" if @restaurant.errors[:name].any? %>">
            <%= f.label :name, "Name" %>
            <br>
            <%= f.text_field :name %>
        </div>
        <div class="field <%= " field_with_errors" if @restaurant.errors[:description].any? %>">
            <%= f.label :description, "Description" %>
            <br>
            <%= f.text_field :description %>
        </div>
        <div class="field <%= " field_with_errors" if @restaurant.errors[:website].any? %>">
            <%= f.label :website, "Website" %>
            <br>
            <%= f.text_field :website %>
        </div>
        <div class="field <%= " field_with_errors" if @restaurant.errors[:phone_number].any? %>">
            <%= f.label :phone_number, "Phone Number" %>
            <br>
            <%= f.text_field :phone_number %>
        </div>
        <div class="field <%= " field_with_errors" if @restaurant.errors[:address].any? %>">
            <%= f.label :address, "Address" %>
            <br>
            <%= f.text_field :address %>
        </div>
        <br>
        <%= f.submit "Submit" %>
    <% end %>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render "form" %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<% if params.has_key?(:user_id) && params[:user_id] == current_user.id.to_s %>
    <br>
    <div class="wrapper">
        <a href="<%= new_restaurant_path %>"><button>New Restaurant</button></a>
    </div>
<% end %>
<br>
<div class="card">
    <div class="container">
        <% if @restaurants.any? %>
            <% @restaurants.each do |restaurant| %>
                <h1><%= link_to restaurant.name, restaurant %></h1>
                <h2><%= truncate(restaurant.description, length: 30) %></h2>
                <br>
            <% end %>
        <% else %>
            <h2>There are currently no restaurants.</h2>
        <% end %>
    </div>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render "form" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1></hr>

<% if @restaurant.user == current_user %>
    <br>
    <div class="wrapper">
        <a href="<%= edit_restaurant_path(@restaurant) %>"><button>Edit</button></a>
        <%= form_for @restaurant, html: { method: :delete } do |f| %>
            <%= f.submit "Delete" %>
        <% end %>
    </div>
    <br>
<% end %>

<h2><%= @restaurant.description %></h2>
<h2>🔗 <%= link_to @restaurant.website, "https://#{@restaurant.website}", target: :_blank %></h2>
<h2>📞 <%= link_to @restaurant.phone_number, "tel:#{@restaurant.phone_number}" %></h2>
<h2>📍 <%= link_to @restaurant.address, "https://maps.google.com/?q=#{@restaurant.address}", target: :_blank %></h2>

<br>
<div class="wrapper">
    <!-- Google Maps Embed -->
    <iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=<%= u @restaurant.address %>&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
</div>

<hr>

<h1><%= link_to "Menus", restaurant_menus_path(@restaurant) %></h1>

<% if @restaurant.user == current_user %>
    <br>
    <div class="wrapper">
        <a href="<%= new_restaurant_menu_path(@restaurant) %>"><button>New Menu</button></a>
    </div>
<% end %>
<br>
<div class="card">
    <div class="container">
        <% if @restaurant.menus.any? %>
            <% @restaurant.menus.each do |menu| %>
                <h1><%= link_to menu.name, menu %></h1>
                <h2><%= truncate(menu.description, length: 30) %></h2>
                <br>
            <% end %>
        <% else %>
            <h2>There are currently no menus.</h2>
        <% end %>
    </div>
</div>