config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :menu_types do
    resources :menus, only: [:index]
  end

  resources :tags do
    resources :menu_items, only: [:index]
  end

  scope "/menu_items" do
    get "dollar_menu", to: "menu_items#dollar_menu"
    get "under_five", to: "menu_items#under_five"
    get "under_ten", to: "menu_items#under_ten"
    get "under_twenty", to: "menu_items#under_twenty"
  end

  resources :menu_items

  resources :menus
  resources :menus do
    resources :menu_items, only: [:index, :new]
  end

  resources :restaurants
  resources :restaurants do
    resources :menus, only: [:index, :new]
  end

  resources :users, except: [:index]
  resources :users do
    resources :restaurants, only: [:index]
    resources :menus, only: [:index]
    resources :menu_items, only: [:index]
  end

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  post "logout", to: "sessions#destroy"

  get "/auth/facebook/callback", to: "sessions#create"

  get "register", to: "users#new"
  post "register", to: "users#create"

  get "about", to: "application#about"
  get "search", to: "application#search"

  root "application#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menu Info</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="page-container">
      <div id="content-wrap">
        <header>
          <a href="/"><img class="logo" src="<%= image_path('logo.png') %>" alt="logo"></a>
          <nav>
            <ul class="nav__links">
              <% if logged_in? %>
                <li><%= link_to "My RESTAURANTS", user_restaurants_path(current_user) %></li>
                <li>|</li>
                <li><%= link_to "My MENUS", user_menus_path(current_user) %></li>
                <li>|</li>
                <li><%= link_to "My ACCOUNT", user_path(current_user) %></li>
              <% else %>
                <li><%= link_to "RESTAURANTS", restaurants_path %></li>
                <li>|</li>
                <li><%= link_to "MENUS", menus_path %></li>
                <li>|</li>
                <li><%= link_to "MENU ITEMS", menu_items_path %></li>
              <% end %>
            </ul>
          </nav>
          <% if logged_in? %>
            <%= form_tag "/logout" do %>
              <%= submit_tag "Logout" %>
            <% end %>
          <% else %>
            <a class="button_small" href="/login"><button>Login</button></a>
          <% end %>
        </header>

        <br>
        <br>
        <%= yield %>
      </div>
      <br>
      <br>
      <br>
      <br>
      <footer>
        <ul>
          <li><a href="/about">ABOUT</a></li>
          <li>|</li>
          <li>Copyright 2020</li>
          <li>|</li>
          <li>Made with ❤ by Stephen McBride</li>
        </ul>
      </footer>
    </div>
  </body>
</html>